INSERT INTO `Size` (tenSize)
SELECT 'S' WHERE NOT EXISTS (SELECT 1 FROM `Size` WHERE tenSize = 'S');
INSERT INTO `Size` (tenSize)
SELECT 'M' WHERE NOT EXISTS (SELECT 1 FROM `Size` WHERE tenSize = 'M');
INSERT INTO `Size` (tenSize)
SELECT 'L' WHERE NOT EXISTS (SELECT 1 FROM `Size` WHERE tenSize = 'L');
INSERT INTO `Size` (tenSize)
SELECT 'XL' WHERE NOT EXISTS (SELECT 1 FROM `Size` WHERE tenSize = 'XL');
INSERT INTO `Size` (tenSize)
SELECT 'XXL' WHERE NOT EXISTS (SELECT 1 FROM `Size` WHERE tenSize = 'XXL');

INSERT INTO phuongThucThanhToan (tenPTTT)
SELECT 'COD' WHERE NOT EXISTS (SELECT 1 FROM phuongThucThanhToan WHERE tenPTTT = 'COD');
INSERT INTO phuongThucThanhToan (tenPTTT)
SELECT 'BANK_TRANSFER' WHERE NOT EXISTS (SELECT 1 FROM phuongThucThanhToan WHERE tenPTTT = 'BANK_TRANSFER');
INSERT INTO phuongThucThanhToan (tenPTTT)
SELECT 'MOMO' WHERE NOT EXISTS (SELECT 1 FROM phuongThucThanhToan WHERE tenPTTT = 'MOMO');
